### ISSUE TITLE
issue/font family

### ISSUE THREAD

**Issue by jcg0** [jcg0/project-1#7]
find a nice font family for app

**Comment by alarbig** [comment]
Some different font's I found that we could use. 

https://fonts.google.com/share?selection.family=Comfortaa%7CHabibi%7CZen%20Dots

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Comfortaa&family=Habibi&family=Zen+Dots&display=swap" rel="stylesheet">

font-family: 'Comfortaa', cursive;
font-family: 'Habibi', serif;
font-family: 'Zen Dots', cursive;

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Comfortaa&family=Habibi&family=Zen+Dots&display=swap" rel="stylesheet">

font-family: 'Comfortaa', cursive;
font-family: 'Habibi', serif;
font-family: 'Zen Dots', cursive;

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Comfortaa&family=Habibi&family=Noto+Nastaliq+Urdu&family=Rajdhani&family=Raleway:ital,wght@0,100;1,900&family=Zen+Dots&display=swap" rel="stylesheet">

font-family: 'Comfortaa', cursive;
font-family: 'Habibi', serif;
font-family: 'Zen Dots', cursive;
